version: "3.8"
services:
  db:
    image: postgres:12.5-alpine
    env_file:
      - db.env
    volumes:
      - type: volume
        source: onyxdb
        target: /pg_data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"

  onyx:
    image: pratuat/onyx:1.0.1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - onyx.env
      - db.env
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=db

  worker:
    image: pratuat/onyx:1.0.1
    command: bash -c "QUEUES=* bundle exec rake resque:work"
    depends_on:
      - db
      - redis
    env_file:
      - onyx.env
      - db.env
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=db

  scheduler:
    image: pratuat/onyx:1.0.1
    command: bash -c "bundle exec rake resque:scheduler"
    depends_on:
      - db
      - redis
    env_file:
      - onyx.env
      - db.env
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=db

volumes:
  onyxdb:
