version: "3.8"
services:
  onyx:
    image: onyx:latest
    environment:
      - MONGODB_HOST=db
    env_file:
      - onyx.env
    depends_on:
      - db

  db:
    image: mongo:latest
    env_file:
      - db.env
    volumes:
      - onyx_test:/etc/mongo
    ports:
      - 27017:27017

volumes:
  onyx_test: