
POST https://newweb.nepalstock.com/api/nots/nepse-data/floorsheet?&sort=contractId,desc HTTP/1.1
Host: newweb.nepalstock.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 10
Origin: https://newweb.nepalstock.com
Connection: keep-alive
Referer: https://newweb.nepalstock.com/floor-sheet
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin


{"id":667}